import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class PdfExportService {
  // Retro palette as PdfColors
  static const PdfColor _pink = PdfColor.fromInt(0xFFFF9CEE);
  static const PdfColor _mint = PdfColor.fromInt(0xFFA1F1B6);
  static const PdfColor _lavender = PdfColor.fromInt(0xFFC4B5FD);
  static const PdfColor _yellow = PdfColor.fromInt(0xFFFDE047);
  static const PdfColor _blue = PdfColor.fromInt(0xFF93C5FD);
  static const PdfColor _orange = PdfColor.fromInt(0xFFFDBA74);

  static Future<Uint8List> generateReport(Map<String, dynamic> result) async {
    final pdf = pw.Document();
    final double score = (result['opportunity_score'] ?? 0).toDouble();
    final Map<String, dynamic> breakdown = (result['score_breakdown'] is Map)
        ? Map<String, dynamic>.from(result['score_breakdown'])
        : {};
    final List<dynamic> loves = result['what_users_love'] ?? [];
    final List<dynamic> hates = result['what_users_hate'] ?? [];
    final List<dynamic> roadmap = result['mvp_roadmap'] ?? [];
    final String pricing = result['pricing_suggestion']?.toString() ?? '';
    final String targetOs = result['target_os_recommendation']?.toString() ?? '';
    final String marketBreakdown = result['market_breakdown']?.toString() ?? '';
    final List<dynamic> competitors = result['competitors_analyzed'] ?? [];
    final List<dynamic> communitySignals = result['community_signals'] ?? [];
    final String category = result['category'] as String? ?? '';
    final String subcategory = result['subcategory'] as String? ?? '';
    final String tam = result['tam'] as String? ?? '';
    final String sam = result['sam'] as String? ?? '';
    final String som = result['som'] as String? ?? '';
    final List<dynamic> revenueModels = result['revenue_model_options'] ?? [];
    final List<dynamic> fundedCompetitors = result['top_funded_competitors'] ?? [];
    final String gtm = result['go_to_market_strategy'] as String? ?? '';
    final String fundingLandscape = result['funding_landscape'] as String? ?? '';

    final boldFont = pw.Font.helveticaBold();
    final normalFont = pw.Font.helvetica();

    final titleStyle = pw.TextStyle(font: boldFont, fontSize: 28);
    final headingStyle = pw.TextStyle(font: boldFont, fontSize: 16);
    final bodyStyle = pw.TextStyle(font: normalFont, fontSize: 11, lineSpacing: 4);
    final smallBoldStyle = pw.TextStyle(font: boldFont, fontSize: 11);

    // Category label map
    const categoryLabels = {
      'mobile_app': 'Mobile App',
      'hardware': 'Hardware',
      'fintech': 'FinTech',
      'saas_web': 'SaaS / Web',
    };

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        footer: (context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          margin: const pw.EdgeInsets.only(top: 10),
          child: pw.Text(
            'Generated by Validatyr  •  ${DateTime.now().toIso8601String().split('T').first}',
            style: pw.TextStyle(font: normalFont, fontSize: 8, color: PdfColors.grey600),
          ),
        ),
        build: (context) => [
          // Header
          pw.Container(
            padding: const pw.EdgeInsets.all(20),
            decoration: pw.BoxDecoration(
              color: _yellow,
              border: pw.Border.all(color: PdfColors.black, width: 2),
            ),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.center,
              children: [
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('VALIDATYR REPORT', style: titleStyle),
                      if (category.isNotEmpty)
                        pw.Padding(
                          padding: const pw.EdgeInsets.only(top: 6),
                          child: pw.Text(
                            '${categoryLabels[category] ?? category}${subcategory.isNotEmpty ? '  •  $subcategory' : ''}',
                            style: pw.TextStyle(font: boldFont, fontSize: 12),
                          ),
                        ),
                      if (targetOs.isNotEmpty)
                        pw.Padding(
                          padding: const pw.EdgeInsets.only(top: 4),
                          child: pw.Text('Target: $targetOs', style: pw.TextStyle(font: normalFont, fontSize: 11)),
                        ),
                    ],
                  ),
                ),
                pw.Container(
                  width: 80,
                  height: 80,
                  decoration: pw.BoxDecoration(
                    color: PdfColors.white,
                    border: pw.Border.all(color: PdfColors.black, width: 2),
                    shape: pw.BoxShape.circle,
                  ),
                  alignment: pw.Alignment.center,
                  child: pw.Column(
                    mainAxisAlignment: pw.MainAxisAlignment.center,
                    children: [
                      pw.Text('${score.toInt()}', style: pw.TextStyle(font: boldFont, fontSize: 32)),
                      pw.Text('/100', style: pw.TextStyle(font: normalFont, fontSize: 9, color: PdfColors.grey700)),
                    ],
                  ),
                ),
              ],
            ),
          ),
          pw.SizedBox(height: 20),

          // Score Breakdown
          if (breakdown.isNotEmpty) ...[
            _sectionHeading('SCORE BREAKDOWN', headingStyle),
            pw.SizedBox(height: 8),
            ..._buildScoreBreakdownRows(breakdown, boldFont, normalFont),
            pw.SizedBox(height: 20),
          ],

          // What Users Hate / Love
          if (hates.isNotEmpty || loves.isNotEmpty) ...[
            pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                if (hates.isNotEmpty)
                  pw.Expanded(
                    child: _buildColoredListBox('WHAT USERS HATE', hates, _pink, headingStyle, bodyStyle, smallBoldStyle),
                  ),
                if (hates.isNotEmpty && loves.isNotEmpty) pw.SizedBox(width: 12),
                if (loves.isNotEmpty)
                  pw.Expanded(
                    child: _buildColoredListBox('WHAT USERS LOVE', loves, _mint, headingStyle, bodyStyle, smallBoldStyle),
                  ),
              ],
            ),
            pw.SizedBox(height: 20),
          ],

          // MVP Roadmap
          if (roadmap.isNotEmpty) ...[
            _buildColoredListBox('DAY-1 MVP ROADMAP', roadmap, _lavender, headingStyle, bodyStyle, smallBoldStyle),
            pw.SizedBox(height: 20),
          ],

          // Community Signals
          if (communitySignals.isNotEmpty) ...[
            _buildColoredListBox('COMMUNITY SIGNALS', communitySignals, _orange, headingStyle, bodyStyle, smallBoldStyle),
            pw.SizedBox(height: 20),
          ],

          // Market Sizing (TAM / SAM / SOM)
          if (tam.isNotEmpty || sam.isNotEmpty || som.isNotEmpty) ...[
            _sectionHeading('MARKET SIZING', headingStyle),
            pw.SizedBox(height: 8),
            pw.Row(children: [
              if (tam.isNotEmpty) pw.Expanded(child: _buildMarketCard('TAM', tam, _yellow, boldFont, normalFont)),
              if (tam.isNotEmpty && sam.isNotEmpty) pw.SizedBox(width: 8),
              if (sam.isNotEmpty) pw.Expanded(child: _buildMarketCard('SAM', sam, _mint, boldFont, normalFont)),
              if ((tam.isNotEmpty || sam.isNotEmpty) && som.isNotEmpty) pw.SizedBox(width: 8),
              if (som.isNotEmpty) pw.Expanded(child: _buildMarketCard('SOM', som, _blue, boldFont, normalFont)),
            ]),
            pw.SizedBox(height: 20),
          ],

          // Revenue Models
          if (revenueModels.isNotEmpty) ...[
            _buildColoredListBox('REVENUE MODELS', revenueModels, _lavender, headingStyle, bodyStyle, smallBoldStyle),
            pw.SizedBox(height: 20),
          ],

          // Funded Competitors
          if (fundedCompetitors.isNotEmpty) ...[
            _sectionHeading('FUNDED COMPETITORS', headingStyle),
            pw.SizedBox(height: 8),
            _buildFundedCompetitorsTable(fundedCompetitors, boldFont, normalFont),
            pw.SizedBox(height: 20),
          ],

          // GTM Strategy
          if (gtm.isNotEmpty) ...[
            _buildColoredTextBox('GO-TO-MARKET STRATEGY', gtm, _orange, headingStyle, bodyStyle),
            pw.SizedBox(height: 20),
          ],

          // Funding Landscape
          if (fundingLandscape.isNotEmpty) ...[
            _buildColoredTextBox('FUNDING LANDSCAPE', fundingLandscape, _blue, headingStyle, bodyStyle),
            pw.SizedBox(height: 20),
          ],

          // Pricing + Market Breakdown
          if (pricing.isNotEmpty || marketBreakdown.isNotEmpty) ...[
            pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                if (pricing.isNotEmpty)
                  pw.Expanded(child: _buildColoredTextBox('PRICING STRATEGY', pricing, _yellow, headingStyle, bodyStyle)),
                if (pricing.isNotEmpty && marketBreakdown.isNotEmpty) pw.SizedBox(width: 12),
                if (marketBreakdown.isNotEmpty)
                  pw.Expanded(child: _buildColoredTextBox('MARKET BREAKDOWN', marketBreakdown, _blue, headingStyle, bodyStyle)),
              ],
            ),
            pw.SizedBox(height: 20),
          ],

          // Competitors Analyzed
          if (competitors.isNotEmpty) ...[
            _sectionHeading('COMPETITORS ANALYZED', headingStyle),
            pw.SizedBox(height: 8),
            pw.Wrap(
              spacing: 8,
              runSpacing: 6,
              children: competitors.map((c) {
                final comp = c is Map ? Map<String, dynamic>.from(c) : <String, dynamic>{};
                final name = comp['title']?.toString() ?? comp['app_id']?.toString() ?? 'Unknown';
                final platform = comp['platform']?.toString().toUpperCase() ?? '';
                return pw.Container(
                  padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.black, width: 1.5),
                    borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
                  ),
                  child: pw.Text(
                    '$name${platform.isNotEmpty ? '  [$platform]' : ''}',
                    style: pw.TextStyle(font: boldFont, fontSize: 10),
                  ),
                );
              }).toList(),
            ),
          ],
        ],
      ),
    );

    return pdf.save();
  }

  // Helper widgets

  static pw.Widget _sectionHeading(String title, pw.TextStyle style) {
    return pw.Text(title, style: style);
  }

  static List<pw.Widget> _buildScoreBreakdownRows(
    Map<String, dynamic> breakdown,
    pw.Font boldFont,
    pw.Font normalFont,
  ) {
    const dimensions = [
      {'key': 'pain_severity', 'label': 'Pain Severity', 'weight': '25%', 'color': _pink},
      {'key': 'market_gap', 'label': 'Market Gap', 'weight': '20%', 'color': _blue},
      {'key': 'mvp_feasibility', 'label': 'MVP Feasibility', 'weight': '15%', 'color': _mint},
      {'key': 'competition_density', 'label': 'Competition', 'weight': '15%', 'color': _lavender},
      {'key': 'monetization_potential', 'label': 'Monetization', 'weight': '10%', 'color': _yellow},
      {'key': 'community_demand', 'label': 'Community Demand', 'weight': '10%', 'color': _blue},
      {'key': 'startup_saturation', 'label': 'Startup Saturation', 'weight': '5%', 'color': _lavender},
    ];

    return dimensions.map((dim) {
      final value = (breakdown[dim['key']] ?? 0).toDouble();
      final color = dim['color'] as PdfColor;
      return pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 6),
        child: pw.Row(children: [
          pw.SizedBox(
            width: 120,
            child: pw.Text(dim['label'] as String, style: pw.TextStyle(font: boldFont, fontSize: 10)),
          ),
          pw.Expanded(
            child: pw.Stack(children: [
              pw.Container(
                height: 12,
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(color: PdfColors.black, width: 1),
                ),
              ),
              pw.Container(
                height: 12,
                width: (value / 100).clamp(0.0, 1.0) * 300,
                color: color,
              ),
            ]),
          ),
          pw.SizedBox(width: 8),
          pw.SizedBox(
            width: 24,
            child: pw.Text('${value.toInt()}', style: pw.TextStyle(font: boldFont, fontSize: 10), textAlign: pw.TextAlign.right),
          ),
          pw.SizedBox(width: 4),
          pw.SizedBox(
            width: 30,
            child: pw.Text('(${dim['weight']})', style: pw.TextStyle(font: normalFont, fontSize: 8, color: PdfColors.grey600)),
          ),
        ]),
      );
    }).toList();
  }

  static pw.Widget _buildColoredListBox(
    String title,
    List<dynamic> items,
    PdfColor bgColor,
    pw.TextStyle headingStyle,
    pw.TextStyle bodyStyle,
    pw.TextStyle smallBoldStyle,
  ) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        color: bgColor,
        border: pw.Border.all(color: PdfColors.black, width: 2),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(title, style: headingStyle.copyWith(fontSize: 13)),
          pw.SizedBox(height: 10),
          ...items.asMap().entries.map((e) => pw.Padding(
                padding: const pw.EdgeInsets.only(bottom: 6),
                child: pw.Row(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Container(
                      width: 18,
                      height: 18,
                      decoration: pw.BoxDecoration(
                        color: PdfColors.black,
                        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(3)),
                      ),
                      alignment: pw.Alignment.center,
                      child: pw.Text('${e.key + 1}', style: pw.TextStyle(font: smallBoldStyle.font!, fontSize: 9, color: PdfColors.white)),
                    ),
                    pw.SizedBox(width: 8),
                    pw.Expanded(child: pw.Text(e.value.toString(), style: bodyStyle)),
                  ],
                ),
              )),
        ],
      ),
    );
  }

  static pw.Widget _buildColoredTextBox(
    String title,
    String content,
    PdfColor bgColor,
    pw.TextStyle headingStyle,
    pw.TextStyle bodyStyle,
  ) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        color: bgColor,
        border: pw.Border.all(color: PdfColors.black, width: 2),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(title, style: headingStyle.copyWith(fontSize: 13)),
          pw.SizedBox(height: 8),
          pw.Text(content, style: bodyStyle),
        ],
      ),
    );
  }

  static pw.Widget _buildMarketCard(String label, String value, PdfColor bgColor, pw.Font boldFont, pw.Font normalFont) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: bgColor,
        border: pw.Border.all(color: PdfColors.black, width: 1.5),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(label, style: pw.TextStyle(font: boldFont, fontSize: 10, letterSpacing: 1)),
          pw.SizedBox(height: 4),
          pw.Text(value, style: pw.TextStyle(font: normalFont, fontSize: 9, lineSpacing: 3)),
        ],
      ),
    );
  }

  static pw.Widget _buildFundedCompetitorsTable(List<dynamic> items, pw.Font boldFont, pw.Font normalFont) {
    return pw.Container(
      decoration: pw.BoxDecoration(
        color: _pink,
        border: pw.Border.all(color: PdfColors.black, width: 2),
      ),
      padding: const pw.EdgeInsets.all(14),
      child: pw.Column(
        children: items.asMap().entries.map((e) {
          final c = e.value is Map ? Map<String, dynamic>.from(e.value as Map) : <String, dynamic>{};
          return pw.Padding(
            padding: pw.EdgeInsets.only(bottom: e.key < items.length - 1 ? 8 : 0),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Container(
                  width: 18,
                  height: 18,
                  decoration: pw.BoxDecoration(
                    color: PdfColors.white,
                    border: pw.Border.all(color: PdfColors.black, width: 1.5),
                    borderRadius: const pw.BorderRadius.all(pw.Radius.circular(3)),
                  ),
                  alignment: pw.Alignment.center,
                  child: pw.Text('${e.key + 1}', style: pw.TextStyle(font: boldFont, fontSize: 9)),
                ),
                pw.SizedBox(width: 8),
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(c['name']?.toString() ?? '', style: pw.TextStyle(font: boldFont, fontSize: 11)),
                      if ((c['funding'] ?? '').toString().isNotEmpty || (c['investors'] ?? '').toString().isNotEmpty)
                        pw.Text(
                          '${c['funding'] ?? ''}${(c['investors'] ?? '').toString().isNotEmpty ? ' · ${c['investors']}' : ''}',
                          style: pw.TextStyle(font: normalFont, fontSize: 9, color: PdfColors.grey700),
                        ),
                    ],
                  ),
                ),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }
}
